### ISSUE TITLE
[FEAT] Add: test streamlit 

### ISSUE THREAD

**Issue by kangsumin2ya** [our-ml-flow/streamlit#2]
## Background
- Add file

## Todo
- [x] Add recent_trade.py file
- [x] Add pages/recommend.py file
- [x] Add pages/wash_trade.py file
- [x] Add pages/whale_info.py file
