### ISSUE TITLE
[FEAT] Add: utils function

### ISSUE THREAD

**Issue by kangsumin2ya** [our-ml-flow/streamlit#5]
## Background
- 기존 코드에서 DB에 연결하거나 여러 페이지에서 공통적으로 사용하는 함수들을 utils.py에 정의하여 정리합니다.

## Todo
- [x] utils.py에 DB 연결 코드 추가 후 코드 수정 (main.py, recommend.py, wash_trade.py, whale_info.py)
- [x] main.py : utils.py에 DB에서 데이터 불러오는 코드 추가 후 코드 수정
- [x] recommend.py : utils.py에 DB에서 데이터 불러오는 코드 추가 후 코드 수정
- [x] wash_trade.py : utils.py에 DB에서 데이터 불러오는 코드 추가 후 코드 수정
- [x] whale_info.py : utils.py에 DB에서 데이터 불러오는 코드 추가 후 코드 수정
