### ISSUE TITLE
[FEAT] Refactor: whole streamlit code

### ISSUE THREAD

**Issue by kangsumin2ya** [our-ml-flow/streamlit#6]
## Background
- 현재 파일마다 중복되는 코드와 여러 기능이 합쳐져 있는 함수가 많고 변수명이나 함수명이 직관적이지 않은 경우가 많습니다.
- 코드 profiling을 진행하기 전에, 위와 같은 이유로 전체적인 streamlit 웹페이지 구현 코드를 수정합니다.

## Todo
- [x] DB 연결 함수를 utils..py파일에서 불러오도록 수정
- [x] 가독성을 위해 SQL문의 함수와 예약어를 대문자화하고 들여쓰기 수정
- [x] if name == "main" 하위에 page 제목과 해당 page 기능을 실행시키는 함수만 추가
- [x] 여러 가지 기능이 합쳐진 함수들을 각각 하나의 기능만 수행하도록 코드 수정
- [x] 이름에서 목적이 명확하게 드러나고 다른 코드와의 통일성이 느껴지도록 함수명, 변수명 수정
